### ISSUE TITLE
Build with CI/CD to ensure prs really work

### ISSUE THREAD

**Issue by dan-r95** [KwatMDPhD/clean_nb#38]
continous delivery with travis CI etc.  would ensure that a merged pull request is really working (from the syntax part) 
and maybe this could be combined with hosting the package on pypi.org

**Comment by KwatME** [comment]
@dan-r95 , I simplified the code base further. I was wondering if you would like to add this feature and submit your pull request. I'm not as familiar with this as you I think. And happy new year!

**Comment by dan-r95** [comment]
Hey @KwatME, I will have a look at it soon I hope. Would be really cool to have a it on PyPi. 
And happy new year to you too!

**Comment by dan-r95** [comment]
I will have a look at this tutorial on how to publish the package!
https://packaging.python.org/tutorials/packaging-projects/

You as the author need to create an account and API token there to upload the package.

For the CI/CD pipeline, github actions is free for public repos, this is awesome!

**Comment by KwatME** [comment]
This tool used to be on pypi but it became cumbersome to maintain. Should we put it back on pypi?

**Comment by dan-r95** [comment]
I dont know what issues occured in the past, but via Github actions, it is possible to automate uploading when the build succeeded
